version: "3.7"

services:
  server:
    image: whyemetl
    container_name: whyemetl_server
    ports:
      - "5000:5000"
    environment:
      PGHOST: db
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
  db:
    image: postgres:9.6
    container_name: whyemetl_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./data/dump.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: postgres
